import { useState, useCallback } from "react";
import { ApiError, NetworkError, api, type AnswerResponse } from "@/lib/api";
import { Loading } from "@/components/shell/Loading";
import { ErrorBoundary } from "@/components/shell/ErrorBoundary";
import { StatusBanner } from "@/components/ui/StatusBanner";
import { VerificationPanel } from "@/components/ui/VerificationPanel";
import { SourceList } from "@/components/ui/SourceCitation";
import { Button } from "@/components/ui/Button";

interface Message {
  id: string;
  role: "user" | "assistant";
  text: string;
  payload?: AnswerResponse;
  error?: string;
  ts: number;
}

function MessageBubble({ message }: { message: Message }) {
  const isUser = message.role === "user";
  const payload = message.payload;

  if (isUser) {
    return (
      <div className="chat__msg chat__msg--user" data-testid="chat-user">
        <div className="chat__bubble">{message.text}</div>
      </div>
    );
  }

  if (message.error) {
    return (
      <div className="chat__msg chat__msg--assistant" data-testid="chat-error">
        <div className="chat__bubble">
          <StatusBanner
            kind="err"
            title="Could not retrieve answer"
            description={message.text}
            testId="message-error"
          />
        </div>
      </div>
    );
  }

  return (
    <div className="chat__msg chat__msg--assistant" data-testid="chat-assistant">
      <div className="chat__bubble">
        <p className="chat__answer" data-testid="chat-answer">
          {message.text}
        </p>

        {payload ? (
          <>
            <VerificationPanel
              verification={payload.verification}
              grounded={payload.grounded}
              className="chat__verification"
              testId="chat-verification"
            />
            <DomainBlock
              primary={payload.primary_domain}
              domains={payload.domains}
              multi={payload.multi_domain}
            />
            {payload.sources && payload.sources.length > 0 ? (
              <SourceList sources={payload.sources} testId="chat-sources" />
            ) : null}
          </>
        ) : null}
      </div>
    </div>
  );
}

function DomainBlock({
  primary,
  domains,
  multi,
}: {
  primary: string;
  domains: string[];
  multi: boolean;
}) {
  if (!primary && (!domains || domains.length === 0)) return null;
  return (
    <div className="chat__domains" data-testid="chat-domains">
      <span className="chat__domain-label">Routed to</span>
      <span className="chat__domain-primary">{primary || "general"}</span>
      {multi && domains && domains.length > 1 ? (
        <span className="chat__domain-multi">+ {domains.length - 1} more</span>
      ) : null}
    </div>
  );
}

export function AssistantPage() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);

  const submit = useCallback(async () => {
    const q = input.trim();
    if (!q || loading) return;

    const userMsg: Message = {
      id: `u-${Date.now()}`,
      role: "user",
      text: q,
      ts: Date.now(),
    };
    setMessages((m) => [...m, userMsg]);
    setInput("");
    setLoading(true);

    try {
      const resp = await api.answer(q);
      const assistantMsg: Message = {
        id: `a-${Date.now()}`,
        role: "assistant",
        text: resp.answer,
        payload: resp,
        ts: Date.now(),
      };
      setMessages((m) => [...m, assistantMsg]);
    } catch (err) {
      const detail =
        err instanceof ApiError || err instanceof NetworkError
          ? err.message
          : "Unexpected error";
      const errMsg: Message = {
        id: `e-${Date.now()}`,
        role: "assistant",
        text: detail,
        error: detail,
        ts: Date.now(),
      };
      setMessages((m) => [...m, errMsg]);
    } finally {
      setLoading(false);
    }
  }, [input, loading]);

  const clear = useCallback(() => {
    setMessages([]);
    setInput("");
  }, []);

  const onKey = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      void submit();
    }
  };

  return (
    <ErrorBoundary>
      <section className="page page--assistant">
        <header className="page__header">
          <div>
            <div className="page__eyebrow page-eyebrow eyebrow">FBR · AI Assistant</div>
            <h2 className="page__title">AI Tax Assistant</h2>
            <p className="page__subtitle">
              Ask natural-language questions about FBR tax and compliance. Answers are generated by the verified backend pipeline (router + RAG + verification).
            </p>
          </div>
          {messages.length > 0 ? (
            <Button variant="ghost" size="sm" onClick={clear} data-testid="assistant-clear">
              Clear conversation
            </Button>
          ) : null}
        </header>

        <div className="chat" data-testid="assistant-chat">
          <div className="chat__messages" data-testid="assistant-messages">
            {messages.length === 0 ? (
              <div className="chat__empty">
                <p>No questions yet. Ask anything about FBR tax, filing obligations, notice types, or compliance timelines.</p>
              </div>
            ) : (
              messages.map((m) => (
                <MessageBubble key={m.id} message={m} />
              ))
            )}
            {loading ? (
              <div className="chat__msg chat__msg--assistant" data-testid="assistant-typing">
                <div className="chat__bubble">
                  <Loading label="Thinking…" testId="assistant-loading" />
                </div>
              </div>
            ) : null}
          </div>

          <form
            className="chat__form"
            onSubmit={(e) => {
              e.preventDefault();
              void submit();
            }}
            data-testid="assistant-form"
          >
            <label htmlFor="assistant-input" className="chat__label">
              Ask a question
            </label>
            <textarea
              id="assistant-input"
              className="chat__textarea"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={onKey}
              placeholder="e.g. What is the penalty for late filing of an annual return?"
              rows={2}
              disabled={loading}
              data-testid="assistant-input"
            />
            <div className="chat__form-actions">
              <span className="chat__hint">Press Enter to send, Shift+Enter for new line.</span>
              <Button
                type="submit"
                variant="primary"
                disabled={!input.trim() || loading}
                loading={loading}
                data-testid="assistant-submit"
              >
                {loading ? "Thinking…" : "Send"}
              </Button>
            </div>
          </form>
        </div>
      </section>
    </ErrorBoundary>
  );
}